version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    environment:
      # For postgres user access w/o password. Obviously not safe but allows easy elevated debugging.
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 25050:5432
    command: [ "-c", "max_connections=200" ]
    volumes:
      - postgres-db:/var/lib/postgresql/data

  mqtt:
      image: eclipse-mosquitto:latest
      container_name: mqtt
      ports:
        - 1883:1883
      restart: unless-stopped

  web:
    image: python:3.8-alpine
    container_name: mqtt_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: "app.py"
    env_file:
      - .env
    depends_on:
      - db
      - mqtt
     
volumes:
  postgres-db: 
    driver: local