version: "3.9"

volumes:
  postgres-db: {}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: "app.py"
    depends_on:
      - db
  
  db:
    image: postgres:14.5-alpine
    environment:
      # For postgres user access w/o password. Obviously not safe but allows easy elevated debugging.
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${POSTGRES_PORT:-25050}:5432
    command: [ "-c", "max_connections=200" ]
    volumes:
      - postgres-db:/var/lib/postgresql/data

  mqtt:
      image: eclipse-mosquitto:latest
      network_mode: bridge
      container_name: mqtt
      expose:
        - 1883
      ports:
        - 1883:1883
      restart: unless-stopped

